basePath: /api/v1
definitions:
  main.LoginState:
    properties:
      token:
        type: string
      userInfo:
        $ref: '#/definitions/main.UserResponse'
        type: object
    type: object
  main.Response:
    properties:
      message:
        type: string
      result:
        type: object
      success:
        type: boolean
    type: object
  main.UserResponse:
    properties:
      createTime:
        type: integer
      id:
        type: string
      loginTime:
        type: integer
      name:
        type: string
      role:
        type: string
      roleId:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login/:
    post:
      consumes:
      - multipart/form-data
      description: Login Description
      parameters:
      - description: 用户
        in: formData
        name: name
        required: true
        type: string
      - description: mima
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: token
              type: string
          schema:
            $ref: '#/definitions/main.LoginState'
        "400":
          description: 需要用户名和密码
          schema:
            $ref: '#/definitions/main.Response'
      summary: Login
      tags:
      - Auth
swagger: "2.0"
